#!/bin/bash

printf "<div class='hours'>"
i=1
while [ $i -lt 6 ]
do
    
hrsTime=$(jq -r --arg i "$i" '.hourly.data[$i|tonumber].time' dkSky.json)
hrsSum=$(jq --arg i "$i" '.hourly.data[$i|tonumber]|.summary' dkSky.json)
hrsClock=$(date "+%I %p" --date=@$hrsTime)
hrsTemp=$(jq --arg i "$i" '.hourly.data[$i|tonumber].temperature' dkSky.json)


printf "$hrsClock"
printf "$hrsSum"
printf '%.0f' $hrsTemp
printf "<br>"
i=$[$i+1]

done
printf "</div>"

minSum=$(jq '.minutely.summary' dkSky.json)
printf "$minSum"
