#!/bin/bash

#php darksky.php
curTime=$(jq '.currently.time' dkSky.json)
curTemp=$(jq '.currently.temperature' dkSky.json)

# get today's high from the "daily" object
tempMax=$(jq '.daily.data[0].temperatureMax' dkSky.json)

windMPH=$(jq '.currently.windSpeed' dkSky.json)
windFrom=$(jq '.currently.windBearing' dkSky.json)
#tempMin=$(jq '.currently.temperatureMin' dkSky.json)
#sunDown=$(jq '.currently.sunsetTime' dkSky.json)
#sunUp=$(jq '.currently.sunriseTime' dkSky.json)
#date "+%Y-%m-%d %H:%M:%S" --date=@$curTime

printf '<div>'
date "+%A %B %e %Y  %r" --date=@$curTime
printf '<br>'
jq '.currently.summary' dkSky.json

printf 'Current temp: %.0f &#x2103; ' $curTemp 
printf '<br>'
printf 'High today: %.0f\n &#x2103; ' $tempMax
printf '<br>'

printf 'Wind %.0f' $windMPH 
printf ' mph'
printf ' from '
printf  $windFrom
printf '&deg\n'
source wind.sh
#printf '\n'
printf '</div> </p>'

## TODO WIND parse degrees into directions
## parse icons into something usefull
